import type { WalmartWorkerEnv } from './env'
import { getWalmartTokenForBrand, upsertWalmartCredentials, verifyBrandAccessToken } from './supabaseAdmin'
import { ensureAccessToken, syncWalmartOrders } from './sync'

function bearerToken(request: Request): string | null {
  const header = request.headers.get('authorization')
  if (!header?.startsWith('Bearer ')) {
    return null
  }
  return header.slice('Bearer '.length)
}

async function requireBrand(
  request: Request,
  env: WalmartWorkerEnv,
  fetchImpl: typeof fetch,
): Promise<string | Response> {
  const token = bearerToken(request)
  if (!token) {
    return Response.json({ error: 'Missing bearer token' }, { status: 401 })
  }
  const brandId = await verifyBrandAccessToken(env, token, fetchImpl)
  if (!brandId) {
    return Response.json({ error: 'Invalid or expired session' }, { status: 401 })
  }
  return brandId
}

/** GET /walmart/status — mirrors handleStatus in worker/src/amazon/handlers.ts:
 * walmart_tokens has zero RLS policies, so this is the frontend's only way
 * to read connection state. Returns only non-secret fields. */
export async function handleStatus(
  request: Request,
  env: WalmartWorkerEnv,
  fetchImpl: typeof fetch = fetch,
): Promise<Response> {
  const brandIdOrResponse = await requireBrand(request, env, fetchImpl)
  if (brandIdOrResponse instanceof Response) {
    return brandIdOrResponse
  }

  const token = await getWalmartTokenForBrand(env, brandIdOrResponse, fetchImpl)
  if (!token) {
    return Response.json({ connected: false })
  }

  return Response.json({ connected: true, lastSyncedAt: token.last_synced_at })
}

/** POST /walmart/connect — stores the brand's own Walmart Seller Center
 * client_id/client_secret. Same shape as Amazon's handleConnect: no OAuth
 * redirect here either — Walmart's client-credentials grant needs only
 * these brand-submitted values, generated by the seller directly in
 * Walmart Seller Center (see the walmart_tokens migration's header
 * comment). Bearer-token-authenticated like every other brand-facing
 * endpoint. */
export async function handleConnect(
  request: Request,
  env: WalmartWorkerEnv,
  fetchImpl: typeof fetch = fetch,
): Promise<Response> {
  const brandIdOrResponse = await requireBrand(request, env, fetchImpl)
  if (brandIdOrResponse instanceof Response) {
    return brandIdOrResponse
  }
  const brandId = brandIdOrResponse

  const body = (await request.json().catch(() => null)) as { clientId?: string; clientSecret?: string } | null
  const clientId = body?.clientId
  const clientSecret = body?.clientSecret
  if (!clientId || !clientSecret) {
    return Response.json({ error: 'clientId and clientSecret are required' }, { status: 400 })
  }

  await upsertWalmartCredentials(env, { brandId, clientId, clientSecret }, fetchImpl)

  return Response.json({ connected: true })
}

/** POST /walmart/sync — manual "sync now" for the calling brand's connected
 * Walmart seller account. Mints/refreshes the access token as needed before
 * fetching orders. */
export async function handleSync(
  request: Request,
  env: WalmartWorkerEnv,
  fetchImpl: typeof fetch = fetch,
): Promise<Response> {
  const brandIdOrResponse = await requireBrand(request, env, fetchImpl)
  if (brandIdOrResponse instanceof Response) {
    return brandIdOrResponse
  }
  const brandId = brandIdOrResponse

  const token = await getWalmartTokenForBrand(env, brandId, fetchImpl)
  if (!token) {
    return Response.json({ error: 'No Walmart seller account connected' }, { status: 400 })
  }

  const accessToken = await ensureAccessToken(
    env,
    {
      brandId,
      clientId: token.client_id,
      clientSecret: token.client_secret,
      cachedAccessToken: token.access_token,
      cachedAccessTokenExpiresAt: token.access_token_expires_at,
    },
    fetchImpl,
  )

  const result = await syncWalmartOrders(
    env,
    { brandId, accessToken, createdStartDate: token.last_synced_at ?? undefined },
    fetchImpl,
  )

  return Response.json(result)
}
